# Site settings
title: GitHub Teacher's Awesome Portfolio
header-img: img/home-bg.jpg
email: services@github.com
copyright_name: Your/Project/Corporate Name
description: "A portfolio for githubteacher"
baseurl:
url: "https://githubteacher.github.io"
twitter_username: githubtraining
github_username:  githubteacher
facebook_username:  github
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

exclude: [vendor]
